### ISSUE TITLE
Getting hyphenation patterns from CTAN.

### ISSUE THREAD

**Issue by daantjie** [mbutterick/hyphenate#4]
My current goal is to add hyphenation support for German – and [I've found the file that TeX uses.](http://mirror.ox.ac.uk/sites/ctan.org/language/hyphenation/dehyph/dehyphn.tex) However, it's not in quite the right format to use with Hyphenate – it does a bit of trickery to keep the whole file in ASCII, whereas we'd like it in Unicode. To add to the trouble, they use *nonstandard* trickery by changing the TeX `catcodes` – the Danish hyphenation file uses a capital X to denote ‘æ’, for example – so that'll inhibit doing it in one fell swoop.

I'll write a parser to clean up dehyphn.tex and put that in a pull request at some point, but **do you think there should be a big push to start adding more languages?** (Given that better will probably increase usage of the package.)

**Comment by mbutterick** [comment]
AFAIK this package has one major user — me. I’m happy to include other languages, of course — see issue #3. But since I don’t read or write those languages (nor TeX), I’m not competent to convert the files, confirm that they work correctly, etc.

**Comment by daantjie** [comment]
Sure — that makes sense. (Thanks for the link to #3.) In that case, I'll double-check what the licensing is for those hyphenation files, and then start converting some of them soon. :)
